'use strict';

const path = require('path');
const { writeFile, formatBytes, percentChange, DIRS } = require('./helpers');

/**
 * Generate a text-based report file for an obfuscated file
 * @param {Object} report - The full report object
 * @returns {Promise<string>} - Path to the saved report file
 */
async function generateReport(report) {
  const lines = [];

  lines.push('═'.repeat(65));
  lines.push(`  OBFUSCATION REPORT — ${report.fileName}`);
  lines.push('═'.repeat(65));
  lines.push('');
  lines.push(`  Language:          ${report.language}`);
  lines.push(`  Level:             ${report.level || 'N/A'}`);
  lines.push(`  Original Size:     ${formatBytes(report.originalSize)}`);
  lines.push(`  Obfuscated Size:   ${formatBytes(report.obfuscatedSize)}`);
  const change = percentChange(report.originalSize, report.obfuscatedSize);
  const prefix = change >= 0 ? '+' : '';
  lines.push(`  Size Change:       ${prefix}${change.toFixed(0)}%`);
  lines.push('');
  lines.push('─'.repeat(65));
  lines.push('  ENTROPY ANALYSIS');
  lines.push('─'.repeat(65));
  lines.push(`  Entropy Before:    ${report.entropyBefore.toFixed(4)} bits/byte`);
  lines.push(`  Entropy After:     ${report.entropyAfter.toFixed(4)} bits/byte`);
  const entropyDiff = report.entropyAfter - report.entropyBefore;
  lines.push(`  Entropy Change:    ${entropyDiff > 0 ? '+' : ''}${entropyDiff.toFixed(4)} bits/byte`);

  const width = 40;
  const beforeFilled = Math.round((report.entropyBefore / 8) * width);
  const afterFilled = Math.round((report.entropyAfter / 8) * width);
  lines.push('');
  lines.push(`  Before: [${'#'.repeat(beforeFilled)}${'.'.repeat(width - beforeFilled)}] ${report.entropyBefore.toFixed(2)}`);
  lines.push(`  After:  [${'#'.repeat(afterFilled)}${'.'.repeat(width - afterFilled)}] ${report.entropyAfter.toFixed(2)}`);

  lines.push('');
  lines.push('─'.repeat(65));
  lines.push('  SECURITY TEST RESULTS');
  lines.push('─'.repeat(65));
  lines.push('');

  lines.push(`  Functionality:     ${report.functionalityPass ? 'PASS' : 'FAIL'} — ${report.functionalityDetail || 'N/A'}`);
  lines.push('');

  lines.push(`  Decodability:      ${report.decodabilityLabel} (score: ${report.decodabilityScore}/100)`);
  if (report.decodabilityDetails && report.decodabilityDetails.length > 0) {
    lines.push('  Surviving techniques:');
    for (const t of report.decodabilityDetails) {
      lines.push(`    • ${t}`);
    }
  }
  lines.push('');

  lines.push(`  String Leakage:    ${report.stringLeakage ? 'WARNING — original strings found' : 'CLEAN — no original strings found'}`);
  lines.push(`  Variable Leakage:  ${report.varLeakage ? 'WARNING — original variable names found' : 'CLEAN — all variables renamed'}`);
  lines.push(`  Reverse Risk:      ${report.reverseRisk}`);

  if (report.staticWarnings && report.staticWarnings.length > 0) {
    lines.push('');
    lines.push('  Warnings:');
    for (const w of report.staticWarnings) {
      lines.push(`    ⚠ ${w}`);
    }
  }

  lines.push('');
  lines.push('═'.repeat(65));
  lines.push(`  Generated by ObfuscateCLI v1.0.0`);
  lines.push(`  ${new Date().toISOString()}`);
  lines.push('═'.repeat(65));

  const content = lines.join('\n');

  const safeName = report.fileName.replace(/\./g, '-');
  const reportPath = path.join(DIRS.output, `report-${safeName}.txt`);
  await writeFile(reportPath, content);

  return reportPath;
}

module.exports = { generateReport };
